changelog:
  exclude:
    labels:
      - dependencies
      - 'major dependencies'
    authors:
      - dependabot
      - dependabot[bot]
      - renovate
      - renovate[bot]
  categories:
    - title: Breaking Changes 🛠
      labels:
        - BREAKING_CHANGE
    - title: New Feature Released 🎉
      labels:
        - new_feature
    - title: Application Improved 🙂
      labels:
        - enhancement
    - title: Bug Fix 🤕
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Build & Deployment
      labels:
        - build
