packages:
  - packages/*

enablePrePostScripts: false

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
minimumReleaseAgeExclude:
  # Renovate security update: hono@4.11.7
  - hono@4.11.7
