name = "ac6-assemble-tool"
compatibility_date = "2024-09-10"

# Cloudflare Pages configuration
pages_build_output_dir = "packages/web/.svelte-kit/output/client"

[vars]
# Environment variables can be defined here

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development" }

# Production configuration  
[env.production]
vars = { ENVIRONMENT = "production" }