version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: ./scripts/ngrok/Node.dockerfile
    command: 'npm run dev -- --port 9000 --host'
    ports:
      - '9000:9000'
    volumes:
      - ../..:/app
  ngrok:
    image: ngrok/ngrok:latest@sha256:8d2d2b134398d186934140626bfa1638e6ae079dc8dd4aaac88707e309406880
    command: 'start --all --config /etc/ngrok.yml'
    ports:
      - '4040:4040'
    volumes:
      - './ngrok.yml:/etc/ngrok.yml'
    env_file:
      - .env
