version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: ./scripts/ngrok/Node.dockerfile
    command: 'npm run dev -- --port 9000 --host'
    ports:
      - '9000:9000'
    volumes:
      - ../..:/app
  ngrok:
    image: ngrok/ngrok:latest@sha256:b7ef69999e774e57ccd9d74a364199ae407563aa7e96cd12d2799bd73a1f355f
    command: 'start --all --config /etc/ngrok.yml'
    ports:
      - '4040:4040'
    volumes:
      - './ngrok.yml:/etc/ngrok.yml'
    env_file:
      - .env
