
// This file is auto-generated by packages/parts/scripts/attributes/generate-attributes-cli.ts
export const armUnitAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "attack_type",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "weapon_type",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "attack_power",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "impact",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "accumulative_impact",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "charge_attack_power",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_impact",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_accumulative_impact",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "direct_hit_adjustment",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "recoil",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ideal_range",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "effective_range",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "rapid_fire",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_time",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "magazine_rounds",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "total_rounds",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "reload_time",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ammunition_cost",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "charge_heat_buildup",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "cooling",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "heat_buildup",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "blast_radius",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_en_load",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_ammo_consumption",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_blast_radius",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "pa_interference",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "guidance",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "homing_lock_time",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "lock_count",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "consecutive_hits",
    "valueType": "numeric",
    "optional": true
  }
] as const
export const backUnitAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "attack_type",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "weapon_type",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "attack_power",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "impact",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "accumulative_impact",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "heat_buildup",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "direct_hit_adjustment",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "recoil",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ideal_range",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "effective_range",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "rapid_fire",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "total_rounds",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "cooling",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ammunition_cost",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "blast_radius",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "reload_time",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_attack_power",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_impact",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_accumulative_impact",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_heat_buildup",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_en_load",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_time",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_ammo_consumption",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "charge_blast_radius",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "pa_interference",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "magazine_rounds",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "guidance",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "homing_lock_time",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "lock_count",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "damage_mitigation",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "impact_dampening",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ig_damage_mitigation",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ig_impact_dampening",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ig_duration",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "deploy_heat_buildup",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "deployment",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "idle_damage_mitigation",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "idle_impact_dampening",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "idle_duration",
    "valueType": "numeric",
    "optional": true
  }
] as const
export const headAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "ap",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_kinetic_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_energy_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_explosive_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "attitude_stability",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "system_recovery",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "scan_distance",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "scan_effect_duration",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "scan_standby_time",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  }
] as const
export const armAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "ap",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_kinetic_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_energy_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_explosive_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "arms_load_limit",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "recoil_control",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "firearm_specialization",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "melee_specialization",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  }
] as const
export const legAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "ap",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_kinetic_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_energy_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_explosive_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "attitude_stability",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "load_limit",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "jump_distance",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "jump_height",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "travel_speed",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "high_speed_performance",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "thrust",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "upward_thrust",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "upward_en_consumption",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "qb_thrust",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "qb_jet_duration",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "qb_en_consumption",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "qb_reload_time",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "qb_reload_ideal_weight",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ab_thrust",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "ab_en_consumption",
    "valueType": "numeric",
    "optional": true
  }
] as const
export const coreAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "ap",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_kinetic_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_energy_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "anti_explosive_defense",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "attitude_stability",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "booster_efficiency_adjective",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "generator_output_adjective",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "generator_supply_adjective",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  }
] as const
export const fcsAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "close_range_assist",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "medium_range_assist",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "long_range_assist",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "missile_lock_correction",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "multi_lock_correction",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  }
] as const
export const boosterAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "thrust",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "upward_thrust",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "upward_en_consumption",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "qb_thrust",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "qb_jet_duration",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "qb_en_consumption",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "qb_reload_time",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "qb_reload_ideal_weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "ab_thrust",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "ab_en_consumption",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "melee_attack_thrust",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "melee_attack_en_consumption",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  }
] as const
export const generatorAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_capacity",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_recharge",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "supply_recovery",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "post_recovery_en_supply",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "energy_firearm_spec",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_output",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  }
] as const
export const expansionAttributes = [
  {
    "attributeName": "classification",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "category",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "manufacture",
    "valueType": "array",
    "optional": false
  },
  {
    "attributeName": "attack_power",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "impact",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "accumulative_impact",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "blast_radius",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "effective_range",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "direct_hit_adjustment",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "price",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "weight",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "en_load",
    "valueType": "numeric",
    "optional": false
  },
  {
    "attributeName": "durability",
    "valueType": "numeric",
    "optional": true
  },
  {
    "attributeName": "time_limit",
    "valueType": "numeric",
    "optional": true
  }
] as const
