import { armUnits, leftArmUnits } from '#parts/arm-units'
import { arms } from '#parts/arms'
import { backUnits, leftBackUnits } from '#parts/back-units'
import { boosters } from '#parts/booster'
import { cores } from '#parts/cores'
import { expansions } from '#parts/expansions'
import { fcses } from '#parts/fces'
import { generators } from '#parts/generators'
import { heads } from '#parts/heads'
import { legs } from '#parts/legs'

import { writeFileSync } from 'fs'
import { resolve } from 'path'

import { excludeAttributes } from './exclude-attributes'

export function main() {
  const attr = excludeParts()
  const contents = buildFileContents(attr)

  writeFileContents(contents)
}

function excludeParts() {
  // units
  const armUnitAttributes = excludeAttributes([...armUnits, ...leftArmUnits])
  const backUnitAttributes = excludeAttributes([...backUnits, ...leftBackUnits])

  // frame
  const headAttributes = excludeAttributes(heads)
  const armAttributes = excludeAttributes(arms)
  const legAttributes = excludeAttributes(legs)
  const coreAttributes = excludeAttributes(cores)

  // inner
  const fcsAttributes = excludeAttributes(fcses)
  const boosterAttributes = excludeAttributes(boosters)
  const generatorAttributes = excludeAttributes(generators)

  // expansion
  const expansionAttributes = excludeAttributes(expansions)

  return {
    armUnitAttributes,
    backUnitAttributes,
    headAttributes,
    armAttributes,
    legAttributes,
    coreAttributes,
    fcsAttributes,
    boosterAttributes,
    generatorAttributes,
    expansionAttributes,
  } as const
}

function buildFileContents(args: ReturnType<typeof excludeParts>): string {
  const {
    armUnitAttributes,
    backUnitAttributes,
    headAttributes,
    armAttributes,
    legAttributes,
    coreAttributes,
    fcsAttributes,
    boosterAttributes,
    generatorAttributes,
    expansionAttributes,
  } = args

  return `
// This file is auto-generated by packages/parts/scripts/attributes/generate-attributes-cli.ts
export const armUnitAttributes = ${JSON.stringify(armUnitAttributes, null, 2)} as const
export const backUnitAttributes = ${JSON.stringify(backUnitAttributes, null, 2)} as const
export const headAttributes = ${JSON.stringify(headAttributes, null, 2)} as const
export const armAttributes = ${JSON.stringify(armAttributes, null, 2)} as const
export const legAttributes = ${JSON.stringify(legAttributes, null, 2)} as const
export const coreAttributes = ${JSON.stringify(coreAttributes, null, 2)} as const
export const fcsAttributes = ${JSON.stringify(fcsAttributes, null, 2)} as const
export const boosterAttributes = ${JSON.stringify(boosterAttributes, null, 2)} as const
export const generatorAttributes = ${JSON.stringify(generatorAttributes, null, 2)} as const
export const expansionAttributes = ${JSON.stringify(expansionAttributes, null, 2)} as const
`
}
function writeFileContents(contents: string): void {
  const thisFilePath = new URL(import.meta.url)
  const targetFilePath = resolve(
    thisFilePath.pathname,
    '../../../src/attributes.ts',
  )

  writeFileSync(targetFilePath, contents, { flag: 'w+' })
}

main()
