name: Lighthouse
on:
  pull_request:
    branches: ["*"]
    paths:
      - packages/core/**
      - packages/parts/**
      - packages/web/**
      - .github/workflows/ci-lighthouse.yml
      - pnpm-lock.yaml

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    permissions:
      contents: read # チェックアウトとビルドのため
    steps:
      # setup
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: setup
        run: pnpm install --frozen-lockfile

      # build
      - run: pnpm run build:test

      # lighthouse
      - name: Run Lighthouse
        run: pnpm dlx @lhci/cli@0.13.x autorun
        working-directory: packages/web
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
