name: Update Package Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-package-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to commit changes
      pull-requests: write
    steps:
      # setup
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          run_install: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Update Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
