name: Web Deploy
on:
  release:
    types:
      - released

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # setup
      - uses: actions/checkout@master
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: setup
        run: npm ci

      - name: build
        run: |
          env_target=packages/web/.env.local
          echo "PUBLIC_REPORT_BUG_URL=${{ vars.REPORT_BUG_URL }}" >> "$env_target"
          echo "PUBLIC_REPORT_REQUEST_URL=${{ vars.REPORT_REQUEST_URL }}" >> "$env_target"
          echo "PUBLIC_LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> "$env_target"

          npm run build
        env:
          ANALYZE_MODE: static
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Upload Contents
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: packages/web/dist
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
